# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .


ARG REACT_APP_API_BASE_URL
ARG REACT_APP_API_VERSION
ARG REACT_APP_REDIRECT_URL

# Set environment variables
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
ENV REACT_APP_API_VERSION=$REACT_APP_API_VERSION
ENV REACT_APP_REDIRECT_URL=$REACT_APP_REDIRECT_URL

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]